String url(languagesController) {
  return "https://$languagesController.wikipedia.org/w/api.php?action=query&format=json&generator=random&grnnamespace=0&prop=extracts|pageimages|info&inprop=url&grnlimit=20&exintro=1&exlimit=max&exsentences=5&explaintext=1&piprop=thumbnail&pithumbsize=400&origin=*";
}
String selectedLanguage = "en";

String aboutUs1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tincidunt nunc in velit facilisis, eu convallis dolor lobortis. Pellentesque at consectetur nisl. Nulla facilisi. Aliquam nibh tortor, bibendum et ante a, eleifend porttitor erat. Curabitur sit amet dolor purus. Nulla convallis sodales lectus, tincidunt finibus arcu ultrices id. Duis ac urna a tortor mollis tempus non a ex. Sed eget porttitor est. Praesent in enim sollicitudin, facilisis mi nec, condimentum sapien.";
String aboutUs2 = "Vivamus quis nisl facilisis, pharetra sem lobortis, dapibus diam. Proin eu ullamcorper nibh. Curabitur pulvinar gravida tellus, eu faucibus lectus hendrerit vitae. Proin lacus dui, luctus eu euismod vel, consectetur ac nisl. Sed volutpat fringilla sem, eget accumsan enim maximus non. Phasellus at nisi vel libero dignissim aliquet ac eu nulla. Proin id luctus sapien. Duis a ligula in est finibus rhoncus sed ac augue. Mauris interdum gravida ante, sed tempus nibh aliquam at. Maecenas maximus eget ex non auctor. Mauris ultrices neque nec accumsan ullamcorper.";
String aboutUs3 = "Vestibulum lacinia erat eu tellus mollis pretium. Sed ultricies tincidunt turpis placerat ultrices. Praesent sit amet nulla sodales, dictum nisi non, accumsan enim. Nulla vel rutrum orci, a aliquam sem. Pellentesque ullamcorper, dolor vitae aliquet pulvinar, leo tellus facilisis quam, et dapibus lectus augue sed leo. Etiam eleifend ipsum eros. Donec malesuada euismod pharetra. Curabitur at dolor sed enim eleifend luctus. Donec feugiat, leo eget cursus ornare, justo lacus ornare elit, eu aliquet neque risus eu dolor. Morbi fermentum turpis et malesuada bibendum. Donec in erat eget eros dictum interdum. Nulla facilisi.";
String aboutUs4 = "Pellentesque eu ullamcorper lorem. Etiam bibendum turpis ac mi interdum, efficitur pulvinar odio viverra. Praesent justo ante, viverra vitae turpis vel, dictum dictum ante. Suspendisse nec maximus sapien. Vestibulum non ante at magna viverra placerat. Phasellus et enim vel lacus sodales imperdiet. Integer ligula tellus, ullamcorper a laoreet ut, viverra lobortis urna. Vestibulum ac faucibus lectus, at ultricies augue. Aliquam porttitor diam et nisi gravida congue. Vivamus tempus turpis dui, eget porta enim porttitor placerat. Proin ultrices, est eget tempor pretium, nisl velit finibus risus, quis scelerisque turpis ex sit amet enim. Nam euismod nisi sed ex elementum, a efficitur odio mollis. Sed ultrices scelerisque tortor, ut facilisis lorem cursus a. Integer in ligula et lacus ultrices gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus.";
String aboutUs5 = "Quisque felis magna, faucibus sit amet lacus ac, mollis convallis nibh. Quisque eget mollis magna. Aenean scelerisque eget nulla id lobortis. Quisque porta vulputate interdum. Nunc odio neque, tincidunt quis vestibulum et, feugiat posuere arcu. Mauris tristique tortor scelerisque tortor porta dictum. Mauris ut finibus quam, id euismod lorem. Etiam semper hendrerit mi, in accumsan libero ornare vehicula. Donec sit amet augue quis leo tincidunt varius id ut leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas luctus, quam eget pharetra ullamcorper, lacus lorem hendrerit velit, in condimentum urna diam eget dui. Proin vitae lacus justo. Quisque finibus, massa volutpat mattis mollis, ligula erat vulputate odio, ac fermentum nisl augue in ligula. Nullam placerat massa quis lacus malesuada vehicula. Curabitur ultricies, sapien et accumsan vehicula, lorem mi luctus sem, vitae blandit velit massa ut tellus.";